# Generated by Django 3.1.2 on 2021-04-27 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogview',
            name='author',
        ),
    ]
