# Generated by Django 3.1.2 on 2021-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_blogview_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogview',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='author_pic'),
        ),
    ]
